on:
  push:
    branches-ignore:
      - release

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: |
          find . -name action.yml | parallel '
            action=$(basename {//})
            cd $action
            echo ::group::$action install deps
            npm ci
            echo ::group::$action lint
            npm run lint
            echo ::group::$action test
            npm test 2>&1
            echo ::group::$action pack
            npm run pack 2>&1
          '
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: |
          git stash -u
          git checkout release || { git checkout -b release && git push -u origin release; }
          git merge master
          git checkout stash^3 .
          GITHUB_REF=release npx \
            -p @semantic-release/changelog \
            -p @semantic-release/git \
            -p conventional-changelog-conventionalcommits \
            -p semantic-release semantic-release
          git push -f origin HEAD:refs/tags/$(git describe --tags --exact-match --abbrev | cut -d. -f1)
        env:
          GITHUB_TOKEN: ${{ github.token }}
